### ISSUE TITLE
feature: add validation on login page

### ISSUE THREAD

**Issue by zacro14** [Hoaveth/mindmate#2]
- ensure to validate the inputs before submitting to back-end
- make a proper(readable) error messages

**Comment by zacro14** [comment]
I would like to  implement this feature

**Comment by Hoaveth** [comment]
Yes you can go ahead and implement this one. Thank you!

**Comment by zacro14** [comment]
I think it should be issue base young mga mag PR so that every one will know the who working on this issue and to avoid merge conflict

**Comment by Hoaveth** [comment]
Thank you for the suggestion! I'll try to update the doc or any merge request.
