### ISSUE TITLE
bug/crash in /features route

### ISSUE THREAD

**Issue by zacro14** [Hoaveth/mindmate#29]
- if the user is not login on the https://mindmate-iota.vercel.app/features the application crashes
- cause of the problems is in side effects it gets the selected features in local storage but the value is undefined

possible solution is authenticate first the user.

**Comment by Hoaveth** [comment]
Yep I have experienced this one too. I'll work on this. We just need to transfer the route checking to _app.jsx.

**Comment by Hoaveth** [comment]
Fix has been deployed to prod.
