### ISSUE TITLE
feat/ highlight the codes terms

### ISSUE THREAD

**Issue by zacro14** [Hoaveth/mindmate#30]
- make sure to add the code terms in **code tag** to know the difference of code terms from the rest 

### Example

`const` = '<code>const</code>'

**Comment by zacro14** [comment]
![not working the reserve world for codes](https://user-images.githubusercontent.com/88084088/227918698-3904a158-3b05-4fe8-b6df-7849a7b5bc64.png)
![fix](https://user-images.githubusercontent.com/88084088/227918729-e65c537a-0a82-4f31-a380-2da8303b40cd.png)


### Fix; on the instance of white space not working on plain jsx without  pre tag

**Comment by Hoaveth** [comment]
Fix was deployed to prod. Kindly check if the changes are applied. Thank you!
